module.exports = {
  name: 'elastic-observability-preso',
  title: 'Elastic Observability',
  slidesDir: 'slides',

  // Customer cut: removed player slides #7,#16,#19,#20,#24,#31,#32,#33
  // Removed files: streams-lake.html, columnar.html, promql.html, migrate.html, nightshift-hero.html, ns-msg-plugplay.html, nightshift-ai-economics.html, nightshift-reveal.html
  slides: [
    "index.html",
    "safe-harbor.html",
    "00-portfolio.html",
    "challenge.html",
    "fy27-pillars.html",
    "streams-intro.html",
    "streams-demo.html",
    "signals-intro.html",
    "logs-pitch.html",
    "doc-store.html",
    "launch.html",
    "what-are-metrics.html",
    "ai-metrics.html",
    "columnar-intro.html",
    "benchmarks.html",
    "one-platform.html",
    "kubernetes.html",
    "plain-english.html",
    "mcp-demo.html",
    "nightshift-intro.html",
    "ns-msg-investigate.html",
    "ns-msg-context.html",
    "06-streams.html",
    "ns-msg-unknowns.html",
    "ns-msg-anywhere.html",
    "thank-you.html"
  ],

  labels: [
    "Cover",
    "Safe Harbor",
    "Portfolio",
    "The Challenge",
    "3 Pillars",
    "Streams Intro",
    "Streams Demo",
    "Signals Intro",
    "Logs Pitch",
    "The Foundation",
    "GA Launch",
    "What Are Metrics?",
    "Metrics \u00d7 AI",
    "25 \u2192 3.75",
    "Benchmarks",
    "One Platform",
    "Kubernetes",
    "Plain English",
    "In Their Agent",
    "Elastic nightshift Intro",
    "NS \u00b7 Investigates",
    "NS \u00b7 Context",
    "Streams",
    "NS \u00b7 Unknowns",
    "NS \u00b7 Anywhere",
    "Thank You"
  ],

  // Original backups + slides hidden for this customer deck
  disabled: [
    "arcs-option-b.html",
    "13-otel-collection.html",
    "05-ai-driven.html",
    "07-ki-demo.html",
    "system-model.html",
    "08-discovery.html",
    "nightshift-architecture.html",
    "nightshift-capabilities.html",
    "nightshift-ai-index.html",
    "nightshift-brain.html",
    "ns-clickthrough-demo.html",
    "nightshift-live-demo.html",
    "streams-lake.html",
    "columnar.html",
    "promql.html",
    "migrate.html",
    "nightshift-hero.html",
    "ns-msg-plugplay.html",
    "nightshift-ai-economics.html",
    "nightshift-reveal.html"
  ],

  port: 3000,
};
